export const ENEMY_TYPES = Object.freeze({
  dog: {
    id: "dog",
    name: "Stray Hound",
    hp: 48,
    speed: 72,
    armorType: "unarmored",
    armor: 0,
    rewardGold: 8,
    damageToBase: 1,
    color: "#c6813e",
    sprite: "dog",
    traits: ["fast"],
    animations: {
      idle: {
        imageSrc: new URL("../assets/enemies/dog-idle.png", import.meta.url).href,
        frames: 4,
        frameWidth: 300,
        frameHeight: 220,
        fps: 5,
        drawWidth: 48,
        drawHeight: 35,
        anchorY: 0.82,
      },
      run: {
        imageSrc: new URL("../assets/enemies/dog-run.png", import.meta.url).href,
        frames: 6,
        frameWidth: 360,
        frameHeight: 240,
        fps: 10,
        drawWidth: 58,
        drawHeight: 39,
        anchorY: 0.8,
      },
      runDown: {
        imageSrc: new URL("../assets/enemies/dog-run-down.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 260,
        fps: 10,
        drawWidth: 42,
        drawHeight: 46,
        anchorY: 0.82,
        flipX: false,
      },
      runUp: {
        imageSrc: new URL("../assets/enemies/dog-run-up.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 260,
        fps: 10,
        drawWidth: 42,
        drawHeight: 46,
        anchorY: 0.82,
        flipX: false,
      },
    },
  },
  boar: {
    id: "boar",
    name: "Wild Boar",
    hp: 78,
    speed: 56,
    armorType: "light",
    armor: 2,
    rewardGold: 9,
    damageToBase: 1,
    color: "#8f4f25",
    sprite: "boar",
    traits: ["sturdy"],
    animations: {
      idle: {
        imageSrc: new URL("../assets/enemies/boar-idle.png", import.meta.url).href,
        frames: 4,
        frameWidth: 300,
        frameHeight: 240,
        fps: 5,
        drawWidth: 54,
        drawHeight: 43,
        anchorY: 0.82,
      },
      run: {
        imageSrc: new URL("../assets/enemies/boar-run.png", import.meta.url).href,
        frames: 6,
        frameWidth: 360,
        frameHeight: 260,
        fps: 10,
        drawWidth: 62,
        drawHeight: 45,
        anchorY: 0.82,
      },
      runDown: {
        imageSrc: new URL("../assets/enemies/boar-run-down.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 300,
        fps: 10,
        drawWidth: 47,
        drawHeight: 54,
        anchorY: 0.83,
        flipX: false,
      },
      runUp: {
        imageSrc: new URL("../assets/enemies/boar-run-up.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 300,
        fps: 10,
        drawWidth: 47,
        drawHeight: 54,
        anchorY: 0.83,
        flipX: false,
      },
    },
  },
  walrus: {
    id: "walrus",
    name: "Walrus Raider",
    hp: 96,
    speed: 48,
    armorType: "light",
    armor: 4,
    rewardGold: 11,
    damageToBase: 1,
    color: "#9c7047",
    sprite: "walrus",
    traits: ["sturdy"],
    animations: {
      idle: {
        imageSrc: new URL("../assets/enemies/walrus-idle.png", import.meta.url).href,
        frames: 4,
        frameWidth: 300,
        frameHeight: 300,
        fps: 5,
        drawWidth: 50,
        drawHeight: 50,
        anchorY: 0.6,
      },
      run: {
        imageSrc: new URL("../assets/enemies/walrus-run.png", import.meta.url).href,
        frames: 6,
        frameWidth: 360,
        frameHeight: 300,
        fps: 10,
        drawWidth: 62,
        drawHeight: 52,
        anchorY: 0.63,
      },
      runDown: {
        imageSrc: new URL("../assets/enemies/walrus-run-down.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 330,
        fps: 10,
        drawWidth: 52,
        drawHeight: 58,
        anchorY: 0.66,
        flipX: false,
      },
      runUp: {
        imageSrc: new URL("../assets/enemies/walrus-run-up.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 330,
        fps: 10,
        drawWidth: 52,
        drawHeight: 58,
        anchorY: 0.66,
        flipX: false,
      },
    },
  },
  murloc: {
    id: "murloc",
    name: "Murloc Skirmisher",
    hp: 58,
    speed: 84,
    armorType: "unarmored",
    armor: 1,
    rewardGold: 8,
    damageToBase: 1,
    color: "#3fae8c",
    sprite: "murloc",
    traits: ["fast"],
    animations: {
      idle: {
        imageSrc: new URL("../assets/enemies/murloc-idle.png", import.meta.url).href,
        frames: 4,
        frameWidth: 300,
        frameHeight: 240,
        fps: 5,
        drawWidth: 42,
        drawHeight: 38,
        anchorY: 0.64,
      },
      run: {
        imageSrc: new URL("../assets/enemies/murloc-run.png", import.meta.url).href,
        frames: 6,
        frameWidth: 360,
        frameHeight: 240,
        fps: 10,
        drawWidth: 54,
        drawHeight: 36,
        anchorY: 0.57,
      },
      runDown: {
        imageSrc: new URL("../assets/enemies/murloc-run-down.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 270,
        fps: 10,
        drawWidth: 44,
        drawHeight: 48,
        anchorY: 0.64,
        flipX: false,
      },
      runUp: {
        imageSrc: new URL("../assets/enemies/murloc-run-up.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 270,
        fps: 10,
        drawWidth: 44,
        drawHeight: 48,
        anchorY: 0.65,
        flipX: false,
      },
    },
  },
  flyingSheep: {
    id: "flyingSheep",
    name: "Flying Sheep",
    hp: 82,
    speed: 68,
    armorType: "magical",
    armor: 0,
    rewardGold: 12,
    damageToBase: 1,
    color: "#ead6a8",
    sprite: "flying-sheep",
    traits: ["flying"],
    animations: {
      idle: {
        imageSrc: new URL("../assets/enemies/flying-sheep-idle.png", import.meta.url).href,
        frames: 4,
        frameWidth: 300,
        frameHeight: 260,
        fps: 6,
        drawWidth: 46,
        drawHeight: 42,
        anchorY: 0.72,
      },
      run: {
        imageSrc: new URL("../assets/enemies/flying-sheep-run.png", import.meta.url).href,
        frames: 6,
        frameWidth: 360,
        frameHeight: 260,
        fps: 10,
        drawWidth: 58,
        drawHeight: 42,
        anchorY: 0.72,
      },
      runDown: {
        imageSrc: new URL("../assets/enemies/flying-sheep-run-down.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 280,
        fps: 10,
        drawWidth: 50,
        drawHeight: 50,
        anchorY: 0.72,
        flipX: false,
      },
      runUp: {
        imageSrc: new URL("../assets/enemies/flying-sheep-run-up.png", import.meta.url).href,
        frames: 6,
        frameWidth: 300,
        frameHeight: 280,
        fps: 10,
        drawWidth: 50,
        drawHeight: 50,
        anchorY: 0.72,
        flipX: false,
      },
    },
  },
  basic: {
    id: "basic",
    name: "Footman",
    hp: 70,
    speed: 58,
    armorType: "light",
    armor: 1,
    rewardGold: 8,
    damageToBase: 1,
    color: "#d8c17a",
    sprite: "circle",
    traits: [],
  },
  fast: {
    id: "fast",
    name: "Runner",
    hp: 52,
    speed: 92,
    armorType: "unarmored",
    armor: 0,
    rewardGold: 9,
    damageToBase: 1,
    color: "#9bd46a",
    sprite: "diamond",
    traits: ["fast"],
  },
  armored: {
    id: "armored",
    name: "Shield Guard",
    hp: 125,
    speed: 45,
    armorType: "heavy",
    armor: 7,
    rewardGold: 14,
    damageToBase: 2,
    color: "#9a9a8f",
    sprite: "hex",
    traits: ["armored"],
  },
  swarm: {
    id: "swarm",
    name: "Creeper",
    hp: 34,
    speed: 76,
    armorType: "unarmored",
    armor: 0,
    rewardGold: 5,
    damageToBase: 1,
    color: "#e5a04d",
    sprite: "small",
    traits: ["swarm"],
  },
  boss: {
    id: "boss",
    name: "Ancient Captain",
    hp: 850,
    speed: 34,
    armorType: "magical",
    armor: 10,
    rewardGold: 90,
    damageToBase: 6,
    color: "#b65353",
    sprite: "boss",
    traits: ["boss", "regen"],
  },
});
