// Balance guide:
// - minDamage/maxDamage are rolled once per shot before armor and type modifiers.
// - upgrade damage is an additive delta to both damage bounds unless minDamage/maxDamage are set.
// - fireRate is attacks per second. Raising it increases projectile count and CPU load.
// - range is in world pixels. One tile is 48 px in the default map.
// - upgrades are additive deltas applied in order. Keep costs higher than the gold
//   earned from one average enemy group to preserve meaningful choices.
// - attackType controls delivery mechanics. damageType controls the attack-vs-armor table.
// - buildTime is construction time in seconds before the tower starts attacking.

export const TARGET_MODES = Object.freeze([
  "first",
  "last",
  "nearest",
  "strongest",
]);

export const TOWER_TYPES = Object.freeze([
  {
    id: "archer",
    name: "Archer Tower",
    description: "Cheap, fast single-target shots.",
    cost: 120,
    buildTime: 1.2,
    sellRatio: 0.7,
    icon: "A",
    color: "#c48a42",
    shape: "arrow",
    sprite: {
      imageSrc: new URL("../assets/towers/archer-tower.png", import.meta.url)
        .href,
      drawWidth: 58,
      drawHeight: 68,
      anchorY: 0.66,
    },
    projectileDY: -30,
    projectileSprite: {
      imageSrc: new URL("../assets/projectiles/arrow.png", import.meta.url)
        .href,
      drawWidth: 28,
      drawHeight: 9,
    },
    range: 150,
    minDamage: 6,
    maxDamage: 10,
    fireRate: 1.35,
    projectileSpeed: 430,
    targetMode: "first",
    attackType: "projectile",
    damageType: "piercing",
    special: {
      slowPercent: 0,
      slowDuration: 0,
      splashRadius: 0,
      poisonDps: 0,
      poisonDuration: 0,
      chainTargets: 0,
      chainFalloff: 0,
    },
    upgrades: [
      {
        name: "Fletching",
        cost: 70,
        damage: 8,
        range: 12,
        fireRate: 0.15,
        projectileSpeed: 40,
      },
      {
        name: "Falcon Aim",
        cost: 130,
        damage: 14,
        range: 16,
        fireRate: 0.2,
        projectileSpeed: 55,
      },
      {
        name: "Volley Crew",
        cost: 230,
        damage: 20,
        range: 20,
        fireRate: 0.35,
        projectileSpeed: 70,
      },
    ],
  },
  {
    id: "cannon",
    name: "Cannon Tower",
    description: "Slow siege blasts with splash damage.",
    cost: 250,
    buildTime: 2.0,
    sellRatio: 0.68,
    icon: "C",
    color: "#6e5a43",
    shape: "cannon",
    sprite: {
      imageSrc: new URL("../assets/towers/canon-tower.png", import.meta.url)
        .href,
      drawWidth: 58,
      drawHeight: 68,
      anchorY: 0.56,
    },
    projectileSprite: {
      imageSrc: new URL("../assets/projectiles/cannonball.png", import.meta.url)
        .href,
      drawWidth: 16,
      drawHeight: 16,
    },
    projectileDX: 10,
    projectileDY: -30,
    range: 135,
    minDamage: 18,
    maxDamage: 20,
    fireRate: 0.62,
    projectileSpeed: 290,
    targetMode: "nearest",
    attackType: "aoe",
    damageType: "siege",
    special: {
      slowPercent: 0,
      slowDuration: 0,
      splashRadius: 58,
      poisonDps: 0,
      poisonDuration: 0,
      chainTargets: 0,
      chainFalloff: 0,
    },
    upgrades: [
      {
        name: "Packed Powder",
        cost: 100,
        damage: 18,
        range: 8,
        fireRate: 0.04,
        special: { splashRadius: 8 },
      },
      {
        name: "Iron Bombs",
        cost: 190,
        damage: 30,
        range: 10,
        fireRate: 0.06,
        special: { splashRadius: 10 },
      },
      {
        name: "Earthshaker",
        cost: 330,
        damage: 48,
        range: 12,
        fireRate: 0.08,
        special: { splashRadius: 14 },
      },
    ],
  },
  {
    id: "frost",
    name: "Frost Tower",
    description: "Low damage, reliable slow.",
    cost: 290,
    buildTime: 1.6,
    sellRatio: 0.7,
    icon: "F",
    color: "#6fd4ff",
    shape: "crystal",
    sprite: {
      imageSrc: new URL("../assets/towers/frost-tower.png", import.meta.url)
        .href,
      drawWidth: 58,
      drawHeight: 68,
      anchorY: 0.56,
    },
    projectileSprite: {
      imageSrc: new URL(
        "../assets/projectiles/frost-shard.png",
        import.meta.url,
      ).href,
      drawWidth: 24,
      drawHeight: 11,
    },
    range: 145,
    minDamage: 6,
    maxDamage: 10,
    fireRate: 0.85,
    projectileSpeed: 360,
    targetMode: "first",
    attackType: "slow",
    damageType: "magic",
    special: {
      slowPercent: 0.35,
      slowDuration: 1.8,
      splashRadius: 38,
      poisonDps: 0,
      poisonDuration: 0,
      chainTargets: 0,
      chainFalloff: 0,
    },
    upgrades: [
      {
        name: "Cold Focus",
        cost: 85,
        damage: 5,
        range: 10,
        fireRate: 0.08,
        special: { slowPercent: 0.05, slowDuration: 0.35 },
      },
      {
        name: "Deep Freeze",
        cost: 160,
        damage: 8,
        range: 12,
        fireRate: 0.1,
        special: { slowPercent: 0.08, slowDuration: 0.45, splashRadius: 8 },
      },
      {
        name: "Winter Spire",
        cost: 280,
        damage: 12,
        range: 18,
        fireRate: 0.12,
        special: { slowPercent: 0.1, slowDuration: 0.6, splashRadius: 12 },
      },
    ],
  },
  {
    id: "magic",
    name: "Magic Tower",
    description: "High single-target magic beam.",
    cost: 480,
    buildTime: 2.2,
    sellRatio: 0.68,
    icon: "M",
    color: "#8c6dff",
    shape: "orb",
    range: 160,
    minDamage: 48,
    maxDamage: 60,
    fireRate: 0.72,
    projectileSpeed: 0,
    targetMode: "strongest",
    attackType: "instant",
    damageType: "magic",
    special: {
      slowPercent: 0,
      slowDuration: 0,
      splashRadius: 0,
      poisonDps: 0,
      poisonDuration: 0,
      chainTargets: 0,
      chainFalloff: 0,
    },
    upgrades: [
      { name: "Bright Rune", cost: 120, damage: 24, range: 10, fireRate: 0.05 },
      { name: "Arc Lens", cost: 230, damage: 42, range: 14, fireRate: 0.08 },
      { name: "Pure Focus", cost: 380, damage: 68, range: 18, fireRate: 0.1 },
    ],
  },
  {
    id: "sentinel",
    name: "Sentinel Post",
    description: "Short-range chain strikes without blocking the road.",
    cost: 640,
    buildTime: 1.8,
    sellRatio: 0.7,
    icon: "S",
    color: "#3f7f89",
    shape: "banner",
    range: 105,
    minDamage: 17,
    maxDamage: 23,
    fireRate: 1.0,
    projectileSpeed: 0,
    targetMode: "nearest",
    attackType: "chain",
    damageType: "chaos",
    special: {
      slowPercent: 0,
      slowDuration: 0,
      splashRadius: 72,
      poisonDps: 0,
      poisonDuration: 0,
      chainTargets: 3,
      chainFalloff: 0.72,
    },
    upgrades: [
      {
        name: "Long Halberds",
        cost: 95,
        damage: 10,
        range: 8,
        fireRate: 0.1,
        special: { chainTargets: 1 },
      },
      {
        name: "Signal Horn",
        cost: 170,
        damage: 16,
        range: 12,
        fireRate: 0.14,
        special: { chainFalloff: 0.08 },
      },
      {
        name: "Elite Watch",
        cost: 300,
        damage: 26,
        range: 15,
        fireRate: 0.18,
        special: { chainTargets: 1 },
      },
    ],
  },
]);

export const TOWERS_BY_ID = Object.freeze(
  Object.fromEntries(TOWER_TYPES.map((tower) => [tower.id, tower])),
);
